-- =====================================================================
-- FINES - Production | 002: Normativi (splošne tabele) + Zasedenost
-- spl_  = splošne tabele, ki jih uporabljajo vsi projekti
-- fp_   = tabele projekta Fines - Production
-- Zaženi PO 001_schema.sql.
-- =====================================================================

-- =====================================================================
-- SPLOŠNO: DRUŽINE IN NORMATIVI
-- =====================================================================

create table if not exists spl_druzine (
  id          bigint generated always as identity primary key,
  koda        text not null unique,          -- npr. OCB, RN-CU, ODC-e
  naziv       text,
  visible     boolean not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- Normativi (ure dela na kos) - prej "Vsi normativi" v Normativi_V2.xlsx
create table if not exists spl_normativi (
  -- "by default": urejevalnik shranjuje spremembe z upsertom po id
  id                    bigint generated by default as identity primary key,
  ident                 text not null unique,                  -- proizvodna šifra artikla
  naziv                 text not null,
  druzina_id            bigint references spl_druzine(id),
  velikost              numeric(10, 2),
  normativ_skupni       numeric(10, 3) not null default 0,     -- h/kos
  normativ_proizvodnja  numeric(10, 3) not null default 0,     -- h/kos (P)
  normativ_montaza      numeric(10, 3) not null default 0,     -- h/kos (M)
  normativ_elektro      numeric(10, 3) not null default 0,     -- h/kos (E)
  normativ_testiranje   numeric(10, 3) not null default 0,     -- h/kos (T)
  barvanje              boolean not null default false,
  cleaning              boolean not null default false,
  opomba                text,
  visible               boolean not null default true,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),
  constraint spl_normativi_nenegativni check (
    normativ_skupni >= 0 and normativ_proizvodnja >= 0 and normativ_montaza >= 0
    and normativ_elektro >= 0 and normativ_testiranje >= 0
  )
);
create index if not exists spl_normativi_druzina_idx on spl_normativi(druzina_id);

-- =====================================================================
-- PROIZVODNJA: ODDELKI ZA ZASEDENOST
-- Obstoječi fp_oddelki dobijo kodo (P/M/E/T) in privzete kapacitete.
-- =====================================================================

alter table fp_oddelki add column if not exists koda text unique;
alter table fp_oddelki add column if not exists privzeto_zaposlenih numeric(6, 2) not null default 0;
alter table fp_oddelki add column if not exists ure_na_dan numeric(5, 2) not null default 6.5;

update fp_oddelki set koda = 'P', privzeto_zaposlenih = 10 where naziv = 'Proizvodnja'     and koda is null;
update fp_oddelki set koda = 'M', privzeto_zaposlenih = 4  where naziv = 'Montaža'         and koda is null;
update fp_oddelki set koda = 'E', privzeto_zaposlenih = 1  where naziv = 'Elektro montaža' and koda is null;
update fp_oddelki set koda = 'T', privzeto_zaposlenih = 1  where naziv = 'Testiranje'      and koda is null;

-- =====================================================================
-- ZASEDENOST: UVOZI NALOGOV
-- Vsak uvoz xlsx je svoj paket. Prikazuje se zadnji aktivni uvoz.
-- Starih uvozov ne brišemo (zgodovina), samo niso več aktivni.
-- =====================================================================

create table if not exists fp_zas_uvozi (
  id           bigint generated always as identity primary key,
  datoteka     text not null,
  st_nalogov   integer not null default 0,
  aktiven      boolean not null default false,  -- aplikacija ga aktivira, ko so vsi nalogi vpisani
  visible      boolean not null default true,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create table if not exists fp_zas_nalogi (
  id                  bigint generated always as identity primary key,
  uvoz_id             bigint not null references fp_zas_uvozi(id),
  st_naloga           text not null,
  krovni_dn           text,
  skupina_dn          text,
  koda_artikla        text not null,
  naziv_artikla       text,
  razpisana_kolicina  numeric(12, 2) not null default 0,
  izdelana_kolicina   numeric(12, 2) not null default 0,
  datum               date,
  datum_pricetka      date,
  rok_izdelave        date,
  narocnik            text,
  status              text,
  tip_naloga          text,
  status_naloga       text,
  pripadnost          text,
  visible             boolean not null default true,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  constraint fp_zas_nalogi_uq unique (uvoz_id, st_naloga)
);
create index if not exists fp_zas_nalogi_uvoz_idx on fp_zas_nalogi(uvoz_id);
create index if not exists fp_zas_nalogi_koda_idx on fp_zas_nalogi(koda_artikla);

-- Ko uvoz postane aktiven, prejšnji uvozi niso več aktivni
create or replace function fp_zas_uvozi_deaktiviraj()
returns trigger
language plpgsql
as $$
begin
  if new.aktiven then
    update fp_zas_uvozi set aktiven = false where id <> new.id and aktiven;
  end if;
  return null;
end;
$$;

drop trigger if exists fp_zas_uvozi_deaktiviraj on fp_zas_uvozi;
create trigger fp_zas_uvozi_deaktiviraj
  after insert or update of aktiven on fp_zas_uvozi
  for each row execute function fp_zas_uvozi_deaktiviraj();

-- =====================================================================
-- ZASEDENOST: KAPACITETE PO TEDNIH
-- Teden = ponedeljek (teden_od). Če za teden ni vnosa, veljajo privzete
-- vrednosti oddelka (privzeto_zaposlenih, ure_na_dan) in 5 delovnih dni.
-- =====================================================================

create table if not exists fp_zas_tedni (
  id             bigint generated always as identity primary key,
  teden_od       date not null unique check (extract(isodow from teden_od) = 1),
  delovnih_dni   numeric(3, 1) not null default 5 check (delovnih_dni between 0 and 7),
  opomba         text,
  visible        boolean not null default true,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create table if not exists fp_zas_kapacitete (
  id              bigint generated always as identity primary key,
  oddelek_id      bigint not null references fp_oddelki(id),
  teden_od        date not null check (extract(isodow from teden_od) = 1),
  st_zaposlenih   numeric(6, 2) not null default 0 check (st_zaposlenih >= 0),
  ure_na_dan      numeric(5, 2) check (ure_na_dan >= 0),   -- null = privzeto oddelka
  visible         boolean not null default true,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  constraint fp_zas_kapacitete_uq unique (oddelek_id, teden_od)
);

-- =====================================================================
-- updated_at + RLS (enako kot v 001: brez DELETE politike)
-- =====================================================================
do $$
declare t text;
begin
  foreach t in array array[
    'spl_druzine', 'spl_normativi', 'fp_zas_uvozi', 'fp_zas_nalogi',
    'fp_zas_tedni', 'fp_zas_kapacitete'
  ] loop
    execute format('drop trigger if exists %I on %I', t || '_updated_at', t);
    execute format(
      'create trigger %I before update on %I for each row execute function fp_set_updated_at()',
      t || '_updated_at', t);

    execute format('alter table %I enable row level security', t);
    execute format('drop policy if exists %I on %I', t || '_select', t);
    execute format('drop policy if exists %I on %I', t || '_insert', t);
    execute format('drop policy if exists %I on %I', t || '_update', t);
    execute format(
      'create policy %I on %I for select to anon, authenticated using (true)', t || '_select', t);
    execute format(
      'create policy %I on %I for insert to anon, authenticated with check (true)', t || '_insert', t);
    execute format(
      'create policy %I on %I for update to anon, authenticated using (true) with check (true)',
      t || '_update', t);
  end loop;
end;
$$;
