-- =====================================================================
-- FINES - Production | 004: Delovni plan (Zasedenost -> Delovni plan)
--
-- Vodja oddelka razporedi krovne naloge na delovna mesta (celice) po dnevih.
-- Trajanje se izračuna iz delovnih ur in kapacitete celice:
--   kapaciteta dneva = število zaposlenih na celici × ure na dan (fp_oddelki.ure_na_dan)
-- Zaženi PO 003_normativi_vsota.sql. Idempotentno.
-- =====================================================================

-- Privzeto število zaposlenih na delovnem mestu (velja za dneve brez posebnega vnosa)
alter table fp_delovna_mesta add column if not exists privzeto_zaposlenih numeric(6, 2) not null default 1
  check (privzeto_zaposlenih >= 0);

-- ---------------------------------------------------------------------
-- Število zaposlenih na delovnem mestu za posamezen dan
-- 0 = celica ta dan ne dela (dopust, praznik ...)
-- ---------------------------------------------------------------------
create table if not exists fp_plan_zaposleni (
  id                bigint generated always as identity primary key,
  delovno_mesto_id  bigint not null references fp_delovna_mesta(id),
  datum             date not null,
  st_zaposlenih     numeric(6, 2) not null default 0 check (st_zaposlenih >= 0),
  visible           boolean not null default true,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  constraint fp_plan_zaposleni_uq unique (delovno_mesto_id, datum)
);
create index if not exists fp_plan_zaposleni_datum_idx on fp_plan_zaposleni(datum);

-- ---------------------------------------------------------------------
-- Postavitve krovnih nalogov na delovna mesta
-- krovni_dn = številka krovnega naloga iz uvoza (ali številka naloga, če krovnega ni).
-- ure = delovne ure, ki jih postavitev porabi (privzeto nerazporejene ure oddelka).
-- Odstranjena postavitev: visible = false.
-- ---------------------------------------------------------------------
create table if not exists fp_plan_postavitve (
  id                bigint generated by default as identity primary key,
  oddelek_id        bigint not null references fp_oddelki(id),
  delovno_mesto_id  bigint not null references fp_delovna_mesta(id),
  krovni_dn         text not null,
  datum_zacetka     date not null,
  ure               numeric(10, 2) not null check (ure > 0),
  opomba            text,
  visible           boolean not null default true,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);
create index if not exists fp_plan_postavitve_oddelek_idx on fp_plan_postavitve(oddelek_id);
create index if not exists fp_plan_postavitve_krovni_idx on fp_plan_postavitve(krovni_dn);

-- =====================================================================
-- updated_at + RLS (enako kot v 001: brez DELETE politike)
-- =====================================================================
do $$
declare t text;
begin
  foreach t in array array['fp_plan_zaposleni', 'fp_plan_postavitve'] loop
    execute format('drop trigger if exists %I on %I', t || '_updated_at', t);
    execute format(
      'create trigger %I before update on %I for each row execute function fp_set_updated_at()',
      t || '_updated_at', t);

    execute format('alter table %I enable row level security', t);
    execute format('drop policy if exists %I on %I', t || '_select', t);
    execute format('drop policy if exists %I on %I', t || '_insert', t);
    execute format('drop policy if exists %I on %I', t || '_update', t);
    execute format(
      'create policy %I on %I for select to anon, authenticated using (true)', t || '_select', t);
    execute format(
      'create policy %I on %I for insert to anon, authenticated with check (true)', t || '_insert', t);
    execute format(
      'create policy %I on %I for update to anon, authenticated using (true) with check (true)',
      t || '_update', t);
  end loop;
end;
$$;
